# Generated by Django 5.1.5 on 2025-07-03 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction', models.CharField(choices=[('CREDITED', 'Credited'), ('DEBITED', 'Debited')], max_length=8)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('RENT', 'Rent'), ('SALARY', 'Salary'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('MEDICAL', 'Medical'), ('UTILITIES', 'Utilities'), ('EDUCATION', 'Education'), ('TRANSPORT', 'Transport'), ('GROCERIES', 'Groceries'), ('INVESTMENT', 'Investment'), ('INSURANCE', 'Insurance'), ('GIFT', 'Gifts'), ('FEES', 'Fees'), ('TAX', 'Taxes'), ('SAVINGS', 'Savings'), ('BONUS', 'Bonus'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
